load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "graphs",
    srcs = [
        "graphs.cpp",
    ],
    hdrs = [
        "graphs.h",
    ],
    visibility = ["//visibility:public"],
)
