cc_binary(
  name = 'mnist_demo',
  srcs = ['main.cc'],
  deps = [
    "@org_tensorflow//tensorflow/cc:scope",
    "@org_tensorflow//tensorflow/cc:client_session",
    "@org_tensorflow//tensorflow/cc:cc_ops",
    "@org_tensorflow//tensorflow/cc:ops",
    "@org_tensorflow//tensorflow/core",
    "@org_tensorflow//tensorflow/core:framework",
    "@org_tensorflow//tensorflow/core:tensorflow",
    "@org_tensorflow//tensorflow/core:lib",
    "@org_tensorflow//tensorflow/core:ops",
    "@org_tensorflow//tensorflow/core/platform:jpeg",
  ],
)