load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cuda_library(
    name = "ccpg",
    srcs = [
        "matrix_multiply.cu",
    ],
    hdrs = [
        "matrix_multiply.h",
    ],
    visibility = ["//visibility:public"],
)
