load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
    name = "lawrencium_lib",
    hdrs = ["common.h"],
    copts = ["-D_LIBCPP_ENABLE_EXPERIMENTAL=1"],
    visibility = ["//visibility:public"],
)
