load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "leetcode",
    srcs = [
        "leetcode.cpp",
    ],
    hdrs = [
        "leetcode.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//common"],
)
