load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cuda_library(
    name = "layers",
    srcs = [
        "convolution.cu",
    ],
    hdrs = [
        "convolution.h",
    ],
    visibility = ["//visibility:public"],
)
