load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ctci",
    srcs = [
        "ctci.cpp",
    ],
    hdrs = [
        "ctci.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//common"],
)
