load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ita",
    hdrs = [
        "dynamic_set.h",
        "heaps.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "sorting",
    hdrs = [
        "sorting.h",
    ],
    visibility = ["//visibility:public"],
)
